[microfiber_jpg]
title = "Microfiber cloth (Mag: 20x*)"
caption = "The magnification is only an estimate."

[gills_jpg]
title = "Gills of Agaricus Bisporus (Mag: 20x*)"
caption = "The magnification is only an estimate."

[spores_jpg]
title = "Spore print"
caption = "Unknown species, but possibly Pluteus Cervinus. | Mag: 40x*"

[card_jpg]
title = "Pokemon card"
caption = "Close-up view of a highly-inked section of a Pokemon card. Note the microabrasions. | Mag: Unknown"
